version: '2'
services:
    nginx:
        image: twang2218/lnmp-nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: twang2218/lnmp-php
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: twang2218/lnmp-mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Passw0rd
        networks:
            - backend
volumes:
    mysql-data: {}
networks:
    frontend:
    backend:
