version: '2'
services:
    php:
      build: ./php/.
      links:
        - mysql:mysql
      volumes:
        - ./php/php.conf:/usr/local/etc/php/conf.d/php.conf:ro
        - ./site:/usr/share/nginx/html:ro
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      links:
        - php
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./site:/usr/share/nginx/html:ro
    mysql:
      image: mysql:latest
      volumes:
        - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - mysql-data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: Passw0rd
volumes:
    mysql-data: {}
