version: '2'
services:
    php:
      build:
        context: .
        dockerfile: Dockerfile-php
      links:
        - mysql:mysql
    nginx:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      ports:
        - "80:80"
      links:
        - php
    mysql:
      build:
        context: .
        dockerfile: Dockerfile-mysql
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: Passw0rd
volumes:
    mysql-data: {}
networks:
    default:
        driver: overlay
