version: '2'
services:
    nginx:
        build:
            context: ./web
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - php
    php:
        build:
            context: ./web
            dockerfile: Dockerfile.php
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: Passw0rd
        command: ['mysqld', '--default-time-zone=Asia/Shanghai']
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
