version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./site:/usr/share/nginx/html:ro
        networks:
            - frontend
    php:
        build: ./php/.
        volumes:
            - ./php/php.conf:/usr/local/etc/php/conf.d/php.conf:ro
            - ./site:/usr/share/nginx/html:ro
        networks:
            - frontend
            - backend
    mysql:
        image: mysql:latest
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Passw0rd
        networks:
            - backend
volumes:
    mysql-data: {}

networks:
    frontend:
    backend:
